// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarket.Database.SqlServer;

#nullable disable

namespace StockMarket.Database.SqlServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230824180633_InitialValue")]
    partial class InitialValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.BuyingSellingShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BuyingSelingShares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 24, 20, 8, 33, 113, DateTimeKind.Local).AddTicks(4168),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4178),
                            Price = 102m
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 24, 20, 9, 33, 113, DateTimeKind.Local).AddTicks(4189),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4190),
                            Price = 107m
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 24, 20, 14, 33, 113, DateTimeKind.Local).AddTicks(4202),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4204),
                            Price = 103.5m
                        });
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HighPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("LowPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Share")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(3977),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4044),
                            Name = "AAPL",
                            OpenPrice = 100m,
                            Share = 150
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4071),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4073),
                            Name = "META",
                            OpenPrice = 234m,
                            Share = 186
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4084),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4085),
                            Name = "MSFT",
                            OpenPrice = 88m,
                            Share = 109
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4136),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4139),
                            Name = "GOOGL",
                            OpenPrice = 321m,
                            Share = 199
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4151),
                            DateUpdated = new DateTime(2023, 8, 24, 20, 6, 33, 113, DateTimeKind.Local).AddTicks(4152),
                            Name = "AMZN",
                            OpenPrice = 118m,
                            Share = 155
                        });
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.CompanyUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Shares")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.Tactics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceFunds")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RiskCoefficient")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TacticsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TacticsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.BuyingSellingShare", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.Company", "Company")
                        .WithMany("BuyingSelingShares")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.CompanyUser", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMarket.Database.SqlServer.Models.User", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.RefreshToken", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.User", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.Tactics", "Tactics")
                        .WithMany()
                        .HasForeignKey("TacticsId");

                    b.Navigation("Tactics");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.Company", b =>
                {
                    b.Navigation("BuyingSelingShares");

                    b.Navigation("CompanyUsers");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.User", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
