// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarket.Database.SqlServer;

#nullable disable

namespace StockMarket.Database.SqlServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Share")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Companys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7066),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7068),
                            Name = "AAPL",
                            Share = 150m
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7110),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7111),
                            Name = "META",
                            Share = 186m
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7121),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7122),
                            Name = "MSFT",
                            Share = 109m
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7131),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7132),
                            Name = "GOOGL",
                            Share = 199m
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7141),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7143),
                            Name = "AMZN",
                            Share = 155m
                        });
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.CompanyUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Shares")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.PriceFluctuations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("PriceFluctuations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 25, 20, 52, 38, 188, DateTimeKind.Local).AddTicks(7166),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7171),
                            Price = 102m
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 25, 20, 53, 38, 188, DateTimeKind.Local).AddTicks(7181),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7184),
                            Price = 107m
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 25, 20, 58, 38, 188, DateTimeKind.Local).AddTicks(7193),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7195),
                            Price = 103.5m
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 25, 20, 58, 38, 188, DateTimeKind.Local).AddTicks(7202),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7204),
                            Price = 102m
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            DateCreated = new DateTime(2023, 8, 25, 20, 58, 38, 188, DateTimeKind.Local).AddTicks(7212),
                            DateUpdated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7213),
                            Price = 104m
                        });
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.Tactics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tactics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(6941),
                            Description = "IF THE CURRENT PRICE IS HIGHER THAN THE AVERAGE PRICE OF THE LAST FIVE INTERVALS",
                            Name = "First"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7024),
                            Description = "FUNDS THAT THE USER HAS * COEFFICIENT = IT IS THE FIGURE WITH WHICH HE BUYS",
                            Name = "Second"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7034),
                            Name = "Third"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7042),
                            Name = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 8, 25, 20, 50, 38, 188, DateTimeKind.Local).AddTicks(7051),
                            Name = "Fifth"
                        });
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceFunds")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RiskCoefficient")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TacticsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TacticsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.CompanyUser", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMarket.Database.SqlServer.Models.User", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.PriceFluctuations", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.Company", "Company")
                        .WithMany("PriceFluctuations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.RefreshToken", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.User", b =>
                {
                    b.HasOne("StockMarket.Database.SqlServer.Models.Tactics", "Tactics")
                        .WithMany()
                        .HasForeignKey("TacticsId");

                    b.Navigation("Tactics");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.Company", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("PriceFluctuations");
                });

            modelBuilder.Entity("StockMarket.Database.SqlServer.Models.User", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
